#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成 YOLO COCO 80 类 ID -> Qwen 词表 Token ID 的映射表（语义 Token 直通）。
运行后输出 C 头文件 yolo_qwen_token_map.h，供端侧多模态 demo 使用，跳过 Tokenizer 与 JSON。
若安装 transformers，会同时生成 prefix/suffix 的 token 序列，否则仅生成 80 类映射。
用法: python3 generate_yolo_qwen_token_map.py [--qwen-dir path/to/Qwen3-1.7B] [--output path/to/yolo_qwen_token_map.h]
"""

import os
import sys
import json
import argparse

try:
    from transformers import AutoTokenizer
    HAS_TRANSFORMERS = True
except ImportError:
    HAS_TRANSFORMERS = False

# COCO 80 类名称，与 yolo-rk3588 config.yaml 顺序一致
COCO_80_CLASSES = [
    "person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
    "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat", "dog",
    "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
    "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite",
    "baseball bat", "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle",
    "wine glass", "cup", "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich",
    "orange", "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa",
    "pottedplant", "bed", "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote",
    "keyboard", "cell phone", "microwave", "oven", "toaster", "sink", "refrigerator", "book",
    "clock", "vase", "scissors", "teddy bear", "hair drier", "toothbrush",
]


def load_vocab_from_tokenizer_json(tokenizer_path: str) -> dict:
    """从 tokenizer.json 的 model.vocab 构建 token -> id 映射（仅简单 token）。"""
    with open(tokenizer_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    vocab = data.get("model", {}).get("vocab", {})
    return vocab


def token_to_id(vocab: dict, token: str) -> int | None:
    """取单个 token 的 id；Qwen 词表里带空格的词多为 Ġ 前缀。"""
    if token in vocab:
        return vocab[token]
    # 空格前缀形式（Qwen/BPE）
    space_token = "Ġ" + token
    if space_token in vocab:
        return vocab[space_token]
    return None


def get_first_token_id_for_phrase(vocab: dict, phrase: str) -> int:
    """
    对短语取「第一个 token」的 id（语义直通时每类用 1 个 token 表示）。
    先尝试整句作为一个 token，否则按空格拆开取第一个词对应的 token。
    """
    # 整句
    tid = token_to_id(vocab, phrase)
    if tid is not None:
        return tid
    # 第一个词
    first_word = phrase.split()[0] if phrase.strip() else phrase
    tid = token_to_id(vocab, first_word)
    if tid is not None:
        return tid
    # 回退：用 0（通常为某个标点）避免未定义
    return 0


def main():
    parser = argparse.ArgumentParser(description="Generate YOLO class_id -> Qwen token_id C header")
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root = os.path.normpath(os.path.join(script_dir, "..", ".."))
    default_qwen = os.path.join(root, "qwen3-1.7b", "Qwen3-1.7B")
    default_out = os.path.join(script_dir, "..", "include", "yolo_qwen_token_map.h")
    parser.add_argument("--qwen-dir", default=default_qwen, help="Qwen tokenizer dir (tokenizer.json)")
    parser.add_argument("--output", default=default_out, help="Output .h path")
    args = parser.parse_args()

    tokenizer_json = os.path.join(args.qwen_dir, "tokenizer.json")
    if not os.path.isfile(tokenizer_json):
        print("Error: tokenizer.json not found at", tokenizer_json, file=sys.stderr)
        sys.exit(1)

    vocab = load_vocab_from_tokenizer_json(tokenizer_json)
    ids = []
    for name in COCO_80_CLASSES:
        tid = get_first_token_id_for_phrase(vocab, name)
        ids.append(tid)

    # Prefix/suffix 用于完整 token 序列：prefix + 检测 token ids + suffix 直接送 RKLLM_INPUT_TOKEN
    prefix_ids, suffix_ids = [], []
    if HAS_TRANSFORMERS:
        try:
            tok = AutoTokenizer.from_pretrained(args.qwen_dir, trust_remote_code=True)
            # 与 Qwen chat 格式一致：<|im_start|>user\n...<|im_end|>\n<|im_start|>assistant\n
            prefix_str = "<|im_start|>user\n图中检测到以下物体："
            suffix_str = "。请用一句话描述画面。<|im_end|>\n<|im_start|>assistant\n"
            enc = tok.encode(prefix_str, add_special_tokens=False)
            prefix_ids = list(enc)
            enc = tok.encode(suffix_str, add_special_tokens=False)
            suffix_ids = list(enc)
        except Exception as e:
            print("Warning: could not encode prefix/suffix:", e, file=sys.stderr)

    out_path = os.path.normpath(args.output)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by scripts/generate_yolo_qwen_token_map.py. Do not edit. */\n")
        f.write("#ifndef YOLO_QWEN_TOKEN_MAP_H\n#define YOLO_QWEN_TOKEN_MAP_H\n\n")
        f.write("/* YOLO COCO 80 class_id -> Qwen token_id，用于语义 Token 直通，跳过 Tokenizer/JSON */\n")
        f.write("#define YOLO_COCO_NUM_CLASSES 80\n\n")
        f.write("static const unsigned int YOLO_CLASS_TO_QWEN_TOKEN_ID[YOLO_COCO_NUM_CLASSES] = {\n")
        for i, tid in enumerate(ids):
            f.write("  %u%s  /* %2d: %s */\n" % (tid, "," if i < len(ids) - 1 else "", i, COCO_80_CLASSES[i]))
        f.write("};\n\n")
        if prefix_ids and suffix_ids:
            f.write("/* Prefix token ids (prompt before detection tokens) */\n")
            f.write("#define PREFIX_TOKEN_LEN %d\n" % len(prefix_ids))
            f.write("static const unsigned int PREFIX_TOKEN_IDS[PREFIX_TOKEN_LEN] = {\n")
            for i, tid in enumerate(prefix_ids):
                f.write("  %u%s\n" % (tid, "," if i < len(prefix_ids) - 1 else ""))
            f.write("};\n\n")
            f.write("/* Suffix token ids (prompt after detection tokens) */\n")
            f.write("#define SUFFIX_TOKEN_LEN %d\n" % len(suffix_ids))
            f.write("static const unsigned int SUFFIX_TOKEN_IDS[SUFFIX_TOKEN_LEN] = {\n")
            for i, tid in enumerate(suffix_ids):
                f.write("  %u%s\n" % (tid, "," if i < len(suffix_ids) - 1 else ""))
            f.write("};\n\n")
        else:
            f.write("/* Install transformers and re-run script to generate PREFIX/SUFFIX_TOKEN_IDS */\n")
            f.write("#define PREFIX_TOKEN_LEN 0\n#define SUFFIX_TOKEN_LEN 0\n")
            f.write("static const unsigned int PREFIX_TOKEN_IDS[1] = {0};\n")
            f.write("static const unsigned int SUFFIX_TOKEN_IDS[1] = {0};\n\n")
        f.write("#endif /* YOLO_QWEN_TOKEN_MAP_H */\n")
    print("Written:", out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
