/* Auto-generated by scripts/generate_yolo_qwen_token_map.py. Do not edit. */
#ifndef YOLO_QWEN_TOKEN_MAP_H
#define YOLO_QWEN_TOKEN_MAP_H

/* YOLO COCO 80 class_id -> Qwen token_id，用于语义 Token 直通，跳过 Tokenizer/JSON */
#define YOLO_COCO_NUM_CLASSES 80

static const unsigned int YOLO_CLASS_TO_QWEN_TOKEN_ID[YOLO_COCO_NUM_CLASSES] = {
  8987,  /*  0: person */
  34986,  /*  1: bicycle */
  6918,  /*  2: car */
  0,  /*  3: motorbike */
  0,  /*  4: aeroplane */
  10338,  /*  5: bus */
  10397,  /*  6: train */
  98318,  /*  7: truck */
  37765,  /*  8: boat */
  53987,  /*  9: traffic light */
  10796,  /* 10: fire hydrant */
  9495,  /* 11: stop sign */
  12921,  /* 12: parking meter */
  27024,  /* 13: bench */
  22592,  /* 14: bird */
  4616,  /* 15: cat */
  18457,  /* 16: dog */
  59675,  /* 17: horse */
  31912,  /* 18: sheep */
  18921,  /* 19: cow */
  45740,  /* 20: elephant */
  67660,  /* 21: bear */
  0,  /* 22: zebra */
  0,  /* 23: giraffe */
  33136,  /* 24: backpack */
  47898,  /* 25: umbrella */
  0,  /* 26: handbag */
  48731,  /* 27: tie */
  87849,  /* 28: suitcase */
  0,  /* 29: frisbee */
  0,  /* 30: skis */
  0,  /* 31: snowboard */
  83560,  /* 32: sports ball */
  98119,  /* 33: kite */
  19507,  /* 34: baseball bat */
  19507,  /* 35: baseball glove */
  97982,  /* 36: skateboard */
  0,  /* 37: surfboard */
  31415,  /* 38: tennis racket */
  16486,  /* 39: bottle */
  71437,  /* 40: wine glass */
  36665,  /* 41: cup */
  44738,  /* 42: fork */
  42720,  /* 43: knife */
  45505,  /* 44: spoon */
  19212,  /* 45: bowl */
  87747,  /* 46: banana */
  22377,  /* 47: apple */
  27874,  /* 48: sandwich */
  34164,  /* 49: orange */
  78176,  /* 50: broccoli */
  74194,  /* 51: carrot */
  10622,  /* 52: hot dog */
  92438,  /* 53: pizza */
  0,  /* 54: donut */
  47384,  /* 55: cake */
  34196,  /* 56: chair */
  31069,  /* 57: sofa */
  0,  /* 58: pottedplant */
  2721,  /* 59: bed */
  0,  /* 60: diningtable */
  26214,  /* 61: toilet */
  0,  /* 62: tvmonitor */
  20638,  /* 63: laptop */
  13237,  /* 64: mouse */
  18147,  /* 65: remote */
  41713,  /* 66: keyboard */
  5873,  /* 67: cell phone */
  41274,  /* 68: microwave */
  16253,  /* 69: oven */
  89818,  /* 70: toaster */
  66738,  /* 71: sink */
  44944,  /* 72: refrigerator */
  2190,  /* 73: book */
  20666,  /* 74: clock */
  92384,  /* 75: vase */
  71624,  /* 76: scissors */
  0,  /* 77: teddy bear */
  50629,  /* 78: hair drier */
  0  /* 79: toothbrush */
};

/* Prefix token ids (prompt before detection tokens) */
#define PREFIX_TOKEN_LEN 10
static const unsigned int PREFIX_TOKEN_IDS[PREFIX_TOKEN_LEN] = {
  151644,
  872,
  198,
  28029,
  15946,
  101978,
  26939,
  87752,
  109840,
  5122
};

/* Suffix token ids (prompt after detection tokens) */
#define SUFFIX_TOKEN_LEN 12
static const unsigned int SUFFIX_TOKEN_IDS[SUFFIX_TOKEN_LEN] = {
  1773,
  14880,
  11622,
  105321,
  53481,
  102650,
  1773,
  151645,
  198,
  151644,
  77091,
  198
};

#endif /* YOLO_QWEN_TOKEN_MAP_H */
